### ISSUE TITLE
Typo fix

### ISSUE THREAD

**Issue by kororro** [NemoKradXNA/MonoGame.Randomchaos.Services#1]
Hi. 

Here
https://nemokradxna.github.io/MonoGame.Randomchaos.Services/index.md
a few typo (cant put PR because I cant find where index.md is).

 I dare say Ill ->  I dare say I'll 

 This project gives you are service that can -> This project gives you a service that can
 
 how cn they be used? -> how can they be used?
 
 using the Transform class in MonoGame.Randomchaos.Intrfaces -> using the Transform class in MonoGame.Randomchaos.Interfaces
 
 similar to how Unity has co routines. -> similar to how Unity has coroutines.

**Comment by NemoKradXNA** [comment]
Ah, excellent thanks for this, my fat fingers strike again lol

I'll get this corrected as soon as I can :)

**Comment by NemoKradXNA** [comment]
Made the changes :)
